// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: agent_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentCommand команда для агента
type AgentCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     int64                  `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	CommandType   string                 `protobuf:"bytes,2,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"` // block_account, block_network, kill_process, quarantine_file, unblock_account, unblock_network
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AlertId       int64                  `protobuf:"varint,4,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"` // ID алерта, который инициировал команду
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Priority      string                 `protobuf:"bytes,6,opt,name=priority,proto3" json:"priority,omitempty"` // low, medium, high, critical
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommand) Reset() {
	*x = AgentCommand{}
	mi := &file_agent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommand) ProtoMessage() {}

func (x *AgentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommand.ProtoReflect.Descriptor instead.
func (*AgentCommand) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{0}
}

func (x *AgentCommand) GetCommandId() int64 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *AgentCommand) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *AgentCommand) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *AgentCommand) GetAlertId() int64 {
	if x != nil {
		return x.AlertId
	}
	return 0
}

func (x *AgentCommand) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AgentCommand) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

// CommandResult результат выполнения команды
type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     int64                  `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"` // описание результата
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`   // ошибка, если была
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_agent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResult) GetCommandId() int64 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResult) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// AgentInfo информация об агенте
type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"` // Windows, Linux
	OsVersion     string                 `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	IpAddress     string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                                                                               // online, offline, error
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // дополнительная информация
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_agent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{2}
}

func (x *AgentInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *AgentInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AgentInfo) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *AgentInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetPendingCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingCommandsRequest) Reset() {
	*x = GetPendingCommandsRequest{}
	mi := &file_agent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingCommandsRequest) ProtoMessage() {}

func (x *GetPendingCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingCommandsRequest.ProtoReflect.Descriptor instead.
func (*GetPendingCommandsRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetPendingCommandsRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetPendingCommandsRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type GetPendingCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*AgentCommand        `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingCommandsResponse) Reset() {
	*x = GetPendingCommandsResponse{}
	mi := &file_agent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingCommandsResponse) ProtoMessage() {}

func (x *GetPendingCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingCommandsResponse.ProtoReflect.Descriptor instead.
func (*GetPendingCommandsResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetPendingCommandsResponse) GetCommands() []*AgentCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type ReportCommandResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *CommandResult         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCommandResultRequest) Reset() {
	*x = ReportCommandResultRequest{}
	mi := &file_agent_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCommandResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCommandResultRequest) ProtoMessage() {}

func (x *ReportCommandResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCommandResultRequest.ProtoReflect.Descriptor instead.
func (*ReportCommandResultRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReportCommandResultRequest) GetResult() *CommandResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ReportCommandResultRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type ReportCommandResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCommandResultResponse) Reset() {
	*x = ReportCommandResultResponse{}
	mi := &file_agent_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCommandResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCommandResultResponse) ProtoMessage() {}

func (x *ReportCommandResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCommandResultResponse.ProtoReflect.Descriptor instead.
func (*ReportCommandResultResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReportCommandResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportCommandResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                                                             // running, idle, busy
	Metrics       map[string]string      `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // cpu_usage, memory_usage, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HeartbeatRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatRequest) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type HeartbeatResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Success               bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NextHeartbeatInterval int32                  `protobuf:"varint,2,opt,name=next_heartbeat_interval,json=nextHeartbeatInterval,proto3" json:"next_heartbeat_interval,omitempty"` // секунды до следующего heartbeat
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetNextHeartbeatInterval() int32 {
	if x != nil {
		return x.NextHeartbeatInterval
	}
	return 0
}

type GetAgentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStatusRequest) Reset() {
	*x = GetAgentStatusRequest{}
	mi := &file_agent_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatusRequest) ProtoMessage() {}

func (x *GetAgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAgentStatusRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetAgentStatusRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type GetAgentStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Agent          *AgentInfo             `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Online         bool                   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	RecentCommands []*CommandResult       `protobuf:"bytes,3,rep,name=recent_commands,json=recentCommands,proto3" json:"recent_commands,omitempty"` // последние N выполненных команд
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAgentStatusResponse) Reset() {
	*x = GetAgentStatusResponse{}
	mi := &file_agent_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatusResponse) ProtoMessage() {}

func (x *GetAgentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAgentStatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetAgentStatusResponse) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *GetAgentStatusResponse) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *GetAgentStatusResponse) GetRecentCommands() []*CommandResult {
	if x != nil {
		return x.RecentCommands
	}
	return nil
}

type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	OsVersion     string                 `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	IpAddress     string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_agent_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterAgentRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterAgentRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterAgentRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *RegisterAgentRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterAgentRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterAgentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RegisterAgentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AgentId         string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	PollingInterval int32                  `protobuf:"varint,4,opt,name=polling_interval,json=pollingInterval,proto3" json:"polling_interval,omitempty"` // секунды между опросами команд
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_agent_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterAgentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterAgentResponse) GetPollingInterval() int32 {
	if x != nil {
		return x.PollingInterval
	}
	return 0
}

var File_agent_service_proto protoreflect.FileDescriptor

const file_agent_service_proto_rawDesc = "" +
	"\n" +
	"\x13agent_service.proto\x12\n" +
	"siem.agent\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcb\x02\n" +
	"\fAgentCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\x03R\tcommandId\x12!\n" +
	"\fcommand_type\x18\x02 \x01(\tR\vcommandType\x12H\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2(.siem.agent.AgentCommand.ParametersEntryR\n" +
	"parameters\x12\x19\n" +
	"\balert_id\x18\x04 \x01(\x03R\aalertId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\tR\bpriority\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb5\x01\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\x03R\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xe9\x02\n" +
	"\tAgentInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\x127\n" +
	"\tlast_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12?\n" +
	"\bmetadata\x18\b \x03(\v2#.siem.agent.AgentInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x19GetPendingCommandsRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\"R\n" +
	"\x1aGetPendingCommandsResponse\x124\n" +
	"\bcommands\x18\x01 \x03(\v2\x18.siem.agent.AgentCommandR\bcommands\"k\n" +
	"\x1aReportCommandResultRequest\x121\n" +
	"\x06result\x18\x01 \x01(\v2\x19.siem.agent.CommandResultR\x06result\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\"Q\n" +
	"\x1bReportCommandResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xec\x01\n" +
	"\x10HeartbeatRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12C\n" +
	"\ametrics\x18\x04 \x03(\v2).siem.agent.HeartbeatRequest.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x126\n" +
	"\x17next_heartbeat_interval\x18\x02 \x01(\x05R\x15nextHeartbeatInterval\"3\n" +
	"\x15GetAgentStatusRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"\xa1\x01\n" +
	"\x16GetAgentStatusResponse\x12+\n" +
	"\x05agent\x18\x01 \x01(\v2\x15.siem.agent.AgentInfoR\x05agent\x12\x16\n" +
	"\x06online\x18\x02 \x01(\bR\x06online\x12B\n" +
	"\x0frecent_commands\x18\x03 \x03(\v2\x19.siem.agent.CommandResultR\x0erecentCommands\"\xae\x02\n" +
	"\x14RegisterAgentRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\x12J\n" +
	"\bmetadata\x18\x06 \x03(\v2..siem.agent.RegisterAgentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x01\n" +
	"\x15RegisterAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12)\n" +
	"\x10polling_interval\x18\x04 \x01(\x05R\x0fpollingInterval2\xd4\x03\n" +
	"\fAgentService\x12c\n" +
	"\x12GetPendingCommands\x12%.siem.agent.GetPendingCommandsRequest\x1a&.siem.agent.GetPendingCommandsResponse\x12f\n" +
	"\x13ReportCommandResult\x12&.siem.agent.ReportCommandResultRequest\x1a'.siem.agent.ReportCommandResultResponse\x12H\n" +
	"\tHeartbeat\x12\x1c.siem.agent.HeartbeatRequest\x1a\x1d.siem.agent.HeartbeatResponse\x12W\n" +
	"\x0eGetAgentStatus\x12!.siem.agent.GetAgentStatusRequest\x1a\".siem.agent.GetAgentStatusResponse\x12T\n" +
	"\rRegisterAgent\x12 .siem.agent.RegisterAgentRequest\x1a!.siem.agent.RegisterAgentResponseB Z\x1esiem-server/proto/agent/pkg/pbb\x06proto3"

var (
	file_agent_service_proto_rawDescOnce sync.Once
	file_agent_service_proto_rawDescData []byte
)

func file_agent_service_proto_rawDescGZIP() []byte {
	file_agent_service_proto_rawDescOnce.Do(func() {
		file_agent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_service_proto_rawDesc), len(file_agent_service_proto_rawDesc)))
	})
	return file_agent_service_proto_rawDescData
}

var file_agent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_agent_service_proto_goTypes = []any{
	(*AgentCommand)(nil),                // 0: siem.agent.AgentCommand
	(*CommandResult)(nil),               // 1: siem.agent.CommandResult
	(*AgentInfo)(nil),                   // 2: siem.agent.AgentInfo
	(*GetPendingCommandsRequest)(nil),   // 3: siem.agent.GetPendingCommandsRequest
	(*GetPendingCommandsResponse)(nil),  // 4: siem.agent.GetPendingCommandsResponse
	(*ReportCommandResultRequest)(nil),  // 5: siem.agent.ReportCommandResultRequest
	(*ReportCommandResultResponse)(nil), // 6: siem.agent.ReportCommandResultResponse
	(*HeartbeatRequest)(nil),            // 7: siem.agent.HeartbeatRequest
	(*HeartbeatResponse)(nil),           // 8: siem.agent.HeartbeatResponse
	(*GetAgentStatusRequest)(nil),       // 9: siem.agent.GetAgentStatusRequest
	(*GetAgentStatusResponse)(nil),      // 10: siem.agent.GetAgentStatusResponse
	(*RegisterAgentRequest)(nil),        // 11: siem.agent.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),       // 12: siem.agent.RegisterAgentResponse
	nil,                                 // 13: siem.agent.AgentCommand.ParametersEntry
	nil,                                 // 14: siem.agent.AgentInfo.MetadataEntry
	nil,                                 // 15: siem.agent.HeartbeatRequest.MetricsEntry
	nil,                                 // 16: siem.agent.RegisterAgentRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),       // 17: google.protobuf.Timestamp
}
var file_agent_service_proto_depIdxs = []int32{
	13, // 0: siem.agent.AgentCommand.parameters:type_name -> siem.agent.AgentCommand.ParametersEntry
	17, // 1: siem.agent.AgentCommand.created_at:type_name -> google.protobuf.Timestamp
	17, // 2: siem.agent.CommandResult.completed_at:type_name -> google.protobuf.Timestamp
	17, // 3: siem.agent.AgentInfo.last_seen:type_name -> google.protobuf.Timestamp
	14, // 4: siem.agent.AgentInfo.metadata:type_name -> siem.agent.AgentInfo.MetadataEntry
	0,  // 5: siem.agent.GetPendingCommandsResponse.commands:type_name -> siem.agent.AgentCommand
	1,  // 6: siem.agent.ReportCommandResultRequest.result:type_name -> siem.agent.CommandResult
	15, // 7: siem.agent.HeartbeatRequest.metrics:type_name -> siem.agent.HeartbeatRequest.MetricsEntry
	2,  // 8: siem.agent.GetAgentStatusResponse.agent:type_name -> siem.agent.AgentInfo
	1,  // 9: siem.agent.GetAgentStatusResponse.recent_commands:type_name -> siem.agent.CommandResult
	16, // 10: siem.agent.RegisterAgentRequest.metadata:type_name -> siem.agent.RegisterAgentRequest.MetadataEntry
	3,  // 11: siem.agent.AgentService.GetPendingCommands:input_type -> siem.agent.GetPendingCommandsRequest
	5,  // 12: siem.agent.AgentService.ReportCommandResult:input_type -> siem.agent.ReportCommandResultRequest
	7,  // 13: siem.agent.AgentService.Heartbeat:input_type -> siem.agent.HeartbeatRequest
	9,  // 14: siem.agent.AgentService.GetAgentStatus:input_type -> siem.agent.GetAgentStatusRequest
	11, // 15: siem.agent.AgentService.RegisterAgent:input_type -> siem.agent.RegisterAgentRequest
	4,  // 16: siem.agent.AgentService.GetPendingCommands:output_type -> siem.agent.GetPendingCommandsResponse
	6,  // 17: siem.agent.AgentService.ReportCommandResult:output_type -> siem.agent.ReportCommandResultResponse
	8,  // 18: siem.agent.AgentService.Heartbeat:output_type -> siem.agent.HeartbeatResponse
	10, // 19: siem.agent.AgentService.GetAgentStatus:output_type -> siem.agent.GetAgentStatusResponse
	12, // 20: siem.agent.AgentService.RegisterAgent:output_type -> siem.agent.RegisterAgentResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_agent_service_proto_init() }
func file_agent_service_proto_init() {
	if File_agent_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_service_proto_rawDesc), len(file_agent_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_service_proto_goTypes,
		DependencyIndexes: file_agent_service_proto_depIdxs,
		MessageInfos:      file_agent_service_proto_msgTypes,
	}.Build()
	File_agent_service_proto = out.File
	file_agent_service_proto_goTypes = nil
	file_agent_service_proto_depIdxs = nil
}
