// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: logs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// формат принимаемых данных
type RequestRawLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PcName        string                 `protobuf:"bytes,2,opt,name=pc_name,json=pcName,proto3" json:"pc_name,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	LogSource     string                 `protobuf:"bytes,4,opt,name=log_source,json=logSource,proto3" json:"log_source,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LogFormat     string                 `protobuf:"bytes,6,opt,name=log_format,json=logFormat,proto3" json:"log_format,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRawLog) Reset() {
	*x = RequestRawLog{}
	mi := &file_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRawLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRawLog) ProtoMessage() {}

func (x *RequestRawLog) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRawLog.ProtoReflect.Descriptor instead.
func (*RequestRawLog) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{0}
}

func (x *RequestRawLog) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RequestRawLog) GetPcName() string {
	if x != nil {
		return x.PcName
	}
	return ""
}

func (x *RequestRawLog) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RequestRawLog) GetLogSource() string {
	if x != nil {
		return x.LogSource
	}
	return ""
}

func (x *RequestRawLog) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RequestRawLog) GetLogFormat() string {
	if x != nil {
		return x.LogFormat
	}
	return ""
}

func (x *RequestRawLog) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// формат ответа от метода сервиса
type ResponseRawLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Response      bool                   `protobuf:"varint,2,opt,name=response,proto3" json:"response,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseRawLog) Reset() {
	*x = ResponseRawLog{}
	mi := &file_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseRawLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRawLog) ProtoMessage() {}

func (x *ResponseRawLog) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRawLog.ProtoReflect.Descriptor instead.
func (*ResponseRawLog) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseRawLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResponseRawLog) GetResponse() bool {
	if x != nil {
		return x.Response
	}
	return false
}

func (x *ResponseRawLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_logs_proto protoreflect.FileDescriptor

const file_logs_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"logs.proto\x12\x04logs\"\xca\x01\n" +
	"\rRequestRawLog\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x17\n" +
	"\apc_name\x18\x02 \x01(\tR\x06pcName\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"log_source\x18\x04 \x01(\tR\tlogSource\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"log_format\x18\x06 \x01(\tR\tlogFormat\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\"V\n" +
	"\x0eResponseRawLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\bR\bresponse\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x8a\x01\n" +
	"\n" +
	"LogService\x129\n" +
	"\n" +
	"SendRawLog\x12\x13.logs.RequestRawLog\x1a\x14.logs.ResponseRawLog\"\x00\x12A\n" +
	"\x10SendRawLogStream\x12\x13.logs.RequestRawLog\x1a\x14.logs.ResponseRawLog\"\x00(\x01B\x0fZ\rserver/pkg/pbb\x06proto3"

var (
	file_logs_proto_rawDescOnce sync.Once
	file_logs_proto_rawDescData []byte
)

func file_logs_proto_rawDescGZIP() []byte {
	file_logs_proto_rawDescOnce.Do(func() {
		file_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logs_proto_rawDesc), len(file_logs_proto_rawDesc)))
	})
	return file_logs_proto_rawDescData
}

var file_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_logs_proto_goTypes = []any{
	(*RequestRawLog)(nil),  // 0: logs.RequestRawLog
	(*ResponseRawLog)(nil), // 1: logs.ResponseRawLog
}
var file_logs_proto_depIdxs = []int32{
	0, // 0: logs.LogService.SendRawLog:input_type -> logs.RequestRawLog
	0, // 1: logs.LogService.SendRawLogStream:input_type -> logs.RequestRawLog
	1, // 2: logs.LogService.SendRawLog:output_type -> logs.ResponseRawLog
	1, // 3: logs.LogService.SendRawLogStream:output_type -> logs.ResponseRawLog
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logs_proto_init() }
func file_logs_proto_init() {
	if File_logs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logs_proto_rawDesc), len(file_logs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logs_proto_goTypes,
		DependencyIndexes: file_logs_proto_depIdxs,
		MessageInfos:      file_logs_proto_msgTypes,
	}.Build()
	File_logs_proto = out.File
	file_logs_proto_goTypes = nil
	file_logs_proto_depIdxs = nil
}
