// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: logs.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogService_SendRawLog_FullMethodName       = "/logs.LogService/SendRawLog"
	LogService_SendRawLogStream_FullMethodName = "/logs.LogService/SendRawLogStream"
)

// LogServiceClient is the client API for LogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// сервис
type LogServiceClient interface {
	// определение метода сервиса с принимаемыми данными и ответом
	// отправка отдного лога
	SendRawLog(ctx context.Context, in *RequestRawLog, opts ...grpc.CallOption) (*ResponseRawLog, error)
	// отправка потока логов
	SendRawLogStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RequestRawLog, ResponseRawLog], error)
}

type logServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogServiceClient(cc grpc.ClientConnInterface) LogServiceClient {
	return &logServiceClient{cc}
}

func (c *logServiceClient) SendRawLog(ctx context.Context, in *RequestRawLog, opts ...grpc.CallOption) (*ResponseRawLog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseRawLog)
	err := c.cc.Invoke(ctx, LogService_SendRawLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) SendRawLogStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RequestRawLog, ResponseRawLog], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LogService_ServiceDesc.Streams[0], LogService_SendRawLogStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RequestRawLog, ResponseRawLog]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogService_SendRawLogStreamClient = grpc.ClientStreamingClient[RequestRawLog, ResponseRawLog]

// LogServiceServer is the server API for LogService service.
// All implementations must embed UnimplementedLogServiceServer
// for forward compatibility.
//
// сервис
type LogServiceServer interface {
	// определение метода сервиса с принимаемыми данными и ответом
	// отправка отдного лога
	SendRawLog(context.Context, *RequestRawLog) (*ResponseRawLog, error)
	// отправка потока логов
	SendRawLogStream(grpc.ClientStreamingServer[RequestRawLog, ResponseRawLog]) error
	mustEmbedUnimplementedLogServiceServer()
}

// UnimplementedLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogServiceServer struct{}

func (UnimplementedLogServiceServer) SendRawLog(context.Context, *RequestRawLog) (*ResponseRawLog, error) {
	return nil, status.Error(codes.Unimplemented, "method SendRawLog not implemented")
}
func (UnimplementedLogServiceServer) SendRawLogStream(grpc.ClientStreamingServer[RequestRawLog, ResponseRawLog]) error {
	return status.Error(codes.Unimplemented, "method SendRawLogStream not implemented")
}
func (UnimplementedLogServiceServer) mustEmbedUnimplementedLogServiceServer() {}
func (UnimplementedLogServiceServer) testEmbeddedByValue()                    {}

// UnsafeLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogServiceServer will
// result in compilation errors.
type UnsafeLogServiceServer interface {
	mustEmbedUnimplementedLogServiceServer()
}

func RegisterLogServiceServer(s grpc.ServiceRegistrar, srv LogServiceServer) {
	// If the following call panics, it indicates UnimplementedLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogService_ServiceDesc, srv)
}

func _LogService_SendRawLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRawLog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).SendRawLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_SendRawLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).SendRawLog(ctx, req.(*RequestRawLog))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_SendRawLogStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LogServiceServer).SendRawLogStream(&grpc.GenericServerStream[RequestRawLog, ResponseRawLog]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogService_SendRawLogStreamServer = grpc.ClientStreamingServer[RequestRawLog, ResponseRawLog]

// LogService_ServiceDesc is the grpc.ServiceDesc for LogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logs.LogService",
	HandlerType: (*LogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRawLog",
			Handler:    _LogService_SendRawLog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendRawLogStream",
			Handler:       _LogService_SendRawLogStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "logs.proto",
}
