agent:
  hostname: ""  
  os: ""    
  interface: "enp0s3"    

server:
  address: "localhost"
  port: "5000"

collectors:
  suricata:
    enabled: false
    log_path: "/var/log/suricata/eve.json"
  
  squid:
    enabled: false
    log_path: "/var/log/squid/access.log"
  
  syslog:
    enabled: false
    log_path: "/var/log/syslog"
  
  auth:
    enabled: false
    log_path: "/var/log/auth.log"